### ISSUE TITLE
Menu item disappears when trying to type command name (Alfred 4.0.7)

### ISSUE THREAD

**Issue by gingerbeardman** [isometry/alfred-man#3] opened 2020-01-06 18:19 UTC
I can type `man<space>` and see the menu item.

But as soon as I start typing the command name I am interested in, say `man wc`, then the menu item disappears and no results can be obtained.

Screen recording: https://imgur.com/a/neDNArt

**Comment by tmerten** [comment] 2020-03-13 11:37
I also have this problem (and its a duplicate of #2 )

**Comment by gingerbeardman** [comment] 2020-03-13 11:59
I switched to a new man workflow https://www.alfredforum.com/topic/14292-alfred-man-man-pages-search-view-terminal-pdf-html/ @tmerten

**Comment by isometry** [comment] 2020-03-14 12:00
Sorry! Missed the notification for this. Now fixed.

**Closed as completed by isometry** 2020-03-14 12:00 UTC

**Comment by gingerbeardman** [comment] 2020-03-14 14:23
I see your fixes are marked as "Catalina" but FWIW I'm still on Mojave and had this issue

**Comment by gnyman** [comment] 2021-06-13 20:57
I had the same issue on Mojave still, not sure if it's just me. Looking at the Alfred debug output I noticed it was failing on a non zero for the `WHATIS_COMMAND`, due to

```
makewhatis: /usr/local/share/man/whatis: Not a directory
makewhatis: /usr/share/man/whatis: Not a directory
```

I whipped together a quick patch https://github.com/gnyman/alfred-man/commit/39d9f9dc256aea3b16134596e92e7c69d96d312f

I can make it in to a PR if it works.
